### ISSUE TITLE
No license is provided

### ISSUE THREAD

**Issue by wflynnvey** [parkerd/statsd-zabbix-backend#10]
Hi, @parkerd 

I appreciate all your work on this module, and I'd like to use it in production environments at my company.  However, the lack of an explicit provided license would preclude me from doing so.  

Could you please provide a license with the module?

Thanks!

**Comment by parkerd** [comment]
I've added the MIT license, thanks for the heads up!

**Comment by wflynnvey** [comment]
Outstanding.  Thank you!!!
