### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by krazibitBD** [parkerd/statsd-zabbix-backend#13]
Please publish current version that uses the `node-zabbix-sender` to npm.
Spent quite some time debugging to realize the difference.
Thanks

**Comment by berlic** [comment]
@parkerd, thank you for you work, very useful! But why is this issue closed?

I spent quite a while to debug

```
Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
```

inside a container until I realised that npm is installing old version that require zabbix_sender util to be present.

I was able to install with

```
npm install node-zabbix-sender
git clone https://github.com/parkerd/statsd-zabbix-backend.git
```

Please, update `npm` package or installation instruction in readme.md

**Comment by parkerd** [comment]
I'm not sure why the issue was closed. A new version has been released with support for node 6+ and the node-zabbix-sender changes.
